# The image will be at "ghcr.io/yourusername/name".
name: utensils

# The native container image to build on top of.
# Warning: Non-uBlue images might not work properly, due to missing components.
base-image: registry.fedoraproject.org/fedora-toolbox

# What Fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated to the next major
# Fedora version, assuming the image you're using as your base container
# builds with the tag (all uBlue images do this).
fedora-version: 38

# This description will be visible in the container metadata.
description: Steve Yackey's custom distrobox.
